import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import gsap from 'gsap';
import ScrollTrigger from 'gsap/dist/ScrollTrigger';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);
  useEffect(()=>{
    gsap.to('.element_3',{
      scrollTrigger:{
        trigger: ".element_3", 
        start: "20px 50%",
        end: "bottom 20px",
        markers: true,
        toggleActions: "restart pause reverse pause"
      },
      x:200,
      rotation:360,
      duration:4
    })
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div className="div_element element_1">
            Element 1
          </div>  
          <div className="div_element element_2">
            Element 2
          </div>  
          <div className="div_element element_3">
            Element 3
          </div>  
        </div>        
      </main>
    </>
  )
}
